name: CI Pipeline Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Status Context
        run: |
          echo "Setting a status context..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Linter
        run: |
          echo "Running linter..."
          exit 1 # Simulate a failure for this check run

      - name: Run Tests
        run: |
          echo "Running tests..."
          echo "Tests passed successfully"

      - name: Build Project
        run: |
          echo "Building the project..."
          sleep 10 # Simulate a long-running check