name: CI Pipeline Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests (Success Example)
        run: echo "Running Tests - Success Case"
    
      - name: Conditional Step
        if: success()
        run: echo "Only Runs on Success"

      - name: Skipped Step
        if: failure()
        run: echo "This step should be skipped"